### ISSUE TITLE
Crtl+C to start a new line

### ISSUE THREAD

**Issue by dmr** [autochthe/react-console#1]
Not really an issue but rather a feature request.

I really like this little console and almost the only thing I miss after the latest update is a way to clear my input:

In bash I can cancel the command I typed by pressing Crtl+C, a new line will be startet and the result will looks like this:

```
> asdf^C
> 
```

What do you think?

**Comment by astralarya** [comment]
I just added support for this.  This should be in the 0.4.0 release.

**Comment by dmr** [comment]
Very cool, thank you!
