### ISSUE TITLE
Cannot write a line without handler

### ISSUE THREAD

**Issue by yuwzho** [autochthe/react-console#5]
I want to put some strings to the console without user input. But it crashes with 

```bash
Uncaught TypeError: Cannot read property 'message' of undefined
    at default_1.log (react-console.js:151)
```

If I input something in the console, and then use a method to call 

```js
myconsole.log('blablabla');
myconsole.return();
```
without input handler to log a line to the console. It can show but the length seems some problem, it can show the `blablabla` and return a new line. But if I call this method once again, the new `blablabla` is append to the old one, ahead of the label

**Comment by yuwzho** [comment]
solved by

```js
myconsole.acceptLine();
myconsole.log('blablabla');
myconsole.return();
```

**Comment by JeSuis** [comment]
that first line causes an error for me

`Unknown command: undefined Type `help` to see a list of supported commands.`

But it does allow me to run the 2nd line whereas it wouldn't before

**Comment by astralarya** [comment]
Could you go into some more detail about this?  It would be helpful if you could provide a minimal example, as well as some details about your environment.
